import { useState } from 'react';
import Card from '../../components/Card';
import Head from 'next/head';
import styled from '@emotion/styled';
import NextLink from 'next/link';
import Container from '../../components/Container';
import { Stack, Heading, Text, SimpleGrid, Divider, Fade } from '@chakra-ui/react';

export default function Projects() {
    const RedText = styled.span`
        color: #D72323;
    `
    const projects = [
        {
            id: 0,
            projectImg: 'https://i.imgur.com/XcNFl03.png',
            title: 'Pieces Shop',
            desc: `Fullstack eCommerce website for imagined furniture store.
            Built with MERN stack (MongoDB, Express, React, Node.js). Features: ability to create accounts, login and logout, adding items to cart, checkout and more.`,
            externalURL: 'https://pieces-shop.netlify.app/',
            githubURL: 'https://github.com/eli-micho/ecommerce_shop',
            tech: ['React', 'Scss', 'React-Redux', 'MongoDB', 'Express', 'Node.js']
        },
        {
            id: 1,
            projectImg: 'https://niagaragrapeandwinetours.ca/wp-content/uploads/2020/09/comingsoon.jpg',
            title: 'Streamer.Info',
            desc: `React App that uses TwitchAPI and returns relevant channel data (e.g follower count, games played, creator status, etc.) based on user searches.
            Built with MERN stack (MongoDB, Express, React, Node.js).`,
            externalURL: 'https://eli-micho.github.io/cryptotracker/',
            githubURL: 'https://github.com/eli-micho/twitch-mern-app',
            tech: ['React', 'Material-UI', 'Express', 'Node.js']
        },
        {
            id: 2,
            projectImg: 'https://i.imgur.com/SV85Tj2.png',
            title: 'CryptoCrunch',
            desc: `Application that displays data from 25+ of the most popular cryptocurrencies: queries API from CoinGecko.com and
            returns relevant data on various cryptocurrency.`,
            externalURL: 'https://eli-micho.github.io/cryptotracker/',
            githubURL: 'https://github.com/eli-micho/cryptotracker',
            tech: ['React', 'Scss', 'React-Redux']
        },
        {
            id: 3,
            projectImg: 'https://i.imgur.com/2KTeiNb.png',
            title: 'Le Cafe',
            desc: 'Simple website for an imagined coffee shop.',
            externalURL: 'https://eli-micho.github.io/restaurant-page/',
            githubURL: 'https://github.com/eli-micho/restaurant-page',
            tech: ['React', 'Scss']
        },
    ]
    return (
        <>
            <Container>
                <Head>
                    <title>Elijah Micho - Software Developer</title>
                    <meta name="title" content="Elijah Micho - Software Developer" />
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Stack
                    spacing={10}
                    justifyContent="center"
                    px={[2, 3]}
                >
                <Fade
                    in={true}
                    transition={{ enter: { duration: 0.4, delay: 0.7 } }}
                >
                    <Stack 
                        spacing={5} 
                        align="center"
                        pt={['5vh', '10vh']}
                        pb={['2.5vh', '3.5vh']}
                    >
                        <Heading
                            fontSize="65px"
                        >
                            Projects
                        </Heading>
                        <Text
                            fontSize="20px"
                            textAlign="center"
                        >
                            I'm constantly working on projects and developing my skills.
                            <br/>
                            Check out my 
                            <RedText> 
                                <NextLink href="https://github.com/eli-micho" passHref isExternal>
                                    &nbsp;Github&nbsp;
                                </NextLink> 
                            </RedText>
                            for more info.
                        </Text>
                        <Divider/>
                    </Stack>
                    <SimpleGrid columns={{ sm: 1, md : 2}} spacing={8}>
                        {projects
                            .map((project) => (
                                <Card
                                    key={project.id}
                                    thumbnail={project.projectImg}
                                    title={project.title}
                                    desc={project.desc}
                                    link={project.externalURL}
                                    github={project.githubURL}
                                    tech={project.tech}
                                />
                            ))
                        }
                    </SimpleGrid>
                    </Fade>
                </Stack>
            </Container>
        </>
    )
}
