import { useState } from 'react';
import Card from '../../components/Card';
import Head from 'next/head';
import styled from '@emotion/styled';
import NextLink from 'next/link';
import Container from '../../components/Container';
import { Stack, Heading, Text, SimpleGrid, Divider, Fade } from '@chakra-ui/react';

export default function Projects() {
    const RedText = styled.span`
        color: #D72323;
    `
    const projects = [
        {
            id: 0,
            projectImg: 'https://i.imgur.com/a/obYMGXZ.png',
            title: 'CryptoCrunch',
            desc: 'Crypto currency tracker',
            externalURL: 'https://eli-micho.github.io/cryptotracker/',
            githubURL: 'https://github.com/eli-micho/cryptotracker',
            tech: ['React', 'Scss']
        },
        {
            id: 1,
            projectImg: 'https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300',
            title: 'CryptoCrunch',
            desc: 'Crypto currency tracker',
            externalURL: 'https://eli-micho.github.io/cryptotracker/',
            githubURL: 'https://github.com/eli-micho/cryptotracker',
            tech: ['React', 'Scss']
        }
    ]
    return (
        <>
            <Container>
                <Head>
                    <title>Elijah Micho - Software Developer</title>
                    <meta name="title" content="Elijah Micho - Software Developer" />
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Stack
                    spacing={10}
                    justifyContent="center"
                    px={[2, 3]}
                >
                <Fade
                    in={true}
                    transition={{ enter: { duration: 0.4, delay: 0.7 } }}
                >
                    <Stack 
                        spacing={5} 
                        align="center"
                        pt={['5vh', '10vh']}
                        pb={['2.5vh', '3.5vh']}
                    >
                        <Heading
                            fontSize="65px"
                        >
                            Projects
                        </Heading>
                        <Text
                            fontSize="20px"
                            textAlign="center"
                        >
                            I'm constantly working on projects and developing my skills.
                            <br/>
                            Check out my 
                            <RedText> 
                                <NextLink href="https://github.com/eli-micho" passHref isExternal>
                                    &nbsp;Github&nbsp;
                                </NextLink> 
                            </RedText>
                            for more info.
                        </Text>
                        <Divider/>
                    </Stack>
                    <SimpleGrid columns={{ sm: 1, md : 2}} spacing={8}>
                        {projects
                            .map((project) => (
                                <Card
                                    key={project.id}
                                    thumbnail={project.projectImg}
                                    title={project.title}
                                    desc={project.desc}
                                    link={project.externalURL}
                                    github={project.githubURL}
                                    tech={project.tech}
                                />
                            ))
                        }
                    </SimpleGrid>
                    </Fade>
                </Stack>
            </Container>
        </>
    )
}
