import Head from 'next/head'
import Image from 'next/image'
import { Stack } from '@chakra-ui/react';
import Container from '../components/Container'
import Introduction from '../components/Introduction';

export default function Home() {
  return (
    <>
      <Container>
        <Head>
          <title>Elijah Micho - Software Developer</title>
          <meta name="title" content="Elijah Micho - Software Developer" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Stack
          as="main"
          justifyContent="center"
        >
          <Introduction/>
        </Stack>
      </Container>
      
    </>
  )
}
