import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/Container'

export default function Home() {
  return (
    <>
      <Container>
        <Head>
          <title>Elijah Micho - Software Developer</title>
          <meta name="title" content="Elijah Micho - Software Developer" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

       
      </Container>
      
    </>
  )
}
